using System.Numerics;

namespace ArmageddonRidge.Core.Models;

/// <summary>
/// Temporary hazard zone that applies damage at the start of turns.
/// </summary>
/// <param name="Center">World-space center of the lingering hazard.</param>
/// <param name="Radius">Hazard radius in world units.</param>
/// <param name="TurnsRemaining">Remaining turn ticks before expiration.</param>
/// <param name="DamagePerTurn">Raw damage applied per turn inside the radius.</param>
/// <param name="VisualKind">Renderer hint for the lingering hazard effect.</param>
/// <param name="OwnerTankId">Tank id credited when this hazard damages the opposing tank.</param>
public sealed record RadiationZone(
    Vector2 Center,
    float Radius,
    int TurnsRemaining,
    float DamagePerTurn,
    ShotVisualKind VisualKind = ShotVisualKind.Nuclear,
    string OwnerTankId = "");

/// <summary>
/// Resolved result of a single explosion, including damage, terrain impact, and renderer hints.
/// </summary>
/// <param name="Center">World-space explosion center.</param>
/// <param name="DamageRadius">Radius used for damage falloff.</param>
/// <param name="TerrainRadius">Radius used for terrain deformation.</param>
/// <param name="PlayerDamage">Raw blast damage dealt to the player tank.</param>
/// <param name="CpuDamage">Raw blast damage dealt to the CPU tank.</param>
/// <param name="DirtAdded">Whether the terrain effect adds dirt rather than removing it.</param>
/// <param name="Nuclear">Whether the explosion should use nuclear-class presentation.</param>
/// <param name="RadiationZones">Lingering zones created by this explosion.</param>
/// <param name="VisualKind">Renderer hint for projectile and explosion styling.</param>
/// <param name="MaxDamageOverride">Optional renderer-only override for effect intensity.</param>
/// <param name="TriggerTrailIndex">Optional trail index where an effect should trigger.</param>
public sealed record ExplosionResult(
    Vector2 Center,
    float DamageRadius,
    float TerrainRadius,
    float PlayerDamage,
    float CpuDamage,
    bool DirtAdded,
    bool Nuclear,
    IReadOnlyList<RadiationZone> RadiationZones,
    ShotVisualKind VisualKind = ShotVisualKind.Ballistic,
    float MaxDamageOverride = 0,
    int TriggerTrailIndex = -1);

/// <summary>
/// Complete deterministic result of firing one weapon for one turn.
/// </summary>
/// <param name="WeaponId">Weapon identifier that was fired.</param>
/// <param name="OwnerTankId">Tank identifier that owned the shot.</param>
/// <param name="Trail">Sampled projectile trail for rendering.</param>
/// <param name="Explosions">Resolved explosions and terrain effects.</param>
/// <param name="Events">Player-facing event log entries generated by the shot.</param>
/// <param name="RoundEnded">Whether the shot ended the round.</param>
/// <param name="Winner">Winning side when the round ended.</param>
/// <param name="Performance">Simulation timing captured for the shot.</param>
/// <param name="VisualKind">Primary renderer hint for the shot.</param>
/// <param name="Intercepted">Whether a defensive intercept cancelled the incoming shot.</param>
/// <param name="InterceptPoint">World-space point used for the defensive intercept effect.</param>
public sealed record ShotResolution(
    string WeaponId,
    string OwnerTankId,
    IReadOnlyList<Vector2> Trail,
    IReadOnlyList<ExplosionResult> Explosions,
    IReadOnlyList<string> Events,
    bool RoundEnded,
    TurnOwner? Winner,
    PerformanceSample Performance,
    ShotVisualKind VisualKind = ShotVisualKind.Ballistic,
    bool Intercepted = false,
    Vector2? InterceptPoint = null);

/// <summary>
/// Timing counters captured around simulation, terrain deformation, and CPU planning.
/// </summary>
/// <param name="SimulationMs">Elapsed shot simulation time in milliseconds.</param>
/// <param name="TerrainMs">Elapsed terrain deformation and explosion resolution time in milliseconds.</param>
/// <param name="CpuPlanningMs">Elapsed CPU planning time in milliseconds.</param>
/// <param name="TrailPoints">Number of sampled projectile trail points.</param>
/// <param name="TerrainColumnsTouched">Number of terrain columns changed by the shot.</param>
public sealed record PerformanceSample(
    double SimulationMs,
    double TerrainMs,
    double CpuPlanningMs,
    int TrailPoints,
    int TerrainColumnsTouched);
